# Generated by Django 4.1.4 on 2023-01-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_alter_ride_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='notes',
            field=models.TextField(default='Test notes'),
            preserve_default=False,
        ),
    ]
