# Generated by Django 4.1.5 on 2023-02-10 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_ride_capacity_ride_num_riders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
