# Generated by Django 4.1.5 on 2023-02-18 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0006_alter_ride_destination_alter_ride_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
