# Generated by Django 4.1.5 on 2023-02-18 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_alter_ride_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='capacity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='num_riders',
            field=models.SmallIntegerField(),
        ),
    ]
