# Generated by Django 4.1.5 on 2023-02-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0007_ride_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride", name="time", field=models.CharField(max_length=100),
        ),
    ]
