# Generated by Django 4.1.5 on 2023-02-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0008_alter_ride_capacity_alter_ride_num_riders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='test',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
