# Generated by Django 4.1.5 on 2023-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0019_riderequest_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
