# Generated by Django 4.1.5 on 2023-03-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0020_riderequest_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
