# Generated by Django 4.1.5 on 2023-03-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0020_riderequest_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop", models.CharField(max_length=100)),
                (
                    "ride",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carpool.ride",
                    ),
                ),
            ],
        ),
    ]
