# Generated by Django 4.1.5 on 2023-03-08 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0021_alter_ride_id_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="ride",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stop",
                to="carpool.ride",
            ),
        ),
    ]
