# Generated by Django 4.1.5 on 2023-02-18 00:44

import carpool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_alter_ride_destination_alter_ride_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='capacity',
            field=models.IntegerField(validators=[carpool.models.validate_positive]),
        ),
    ]
