# Generated by Django 4.1.5 on 2023-02-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0009_ride_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='test',
        ),
    ]
