# Generated by Django 4.1.5 on 2023-02-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0011_alter_ride_num_riders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
