# Generated by Django 4.1.5 on 2023-02-18 03:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0008_alter_ride_time"),
        ("carpool", "0012_alter_ride_capacity"),
    ]

    operations = []

