# Generated by Django 4.1.5 on 2023-02-18 03:49

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0013_merge_0008_alter_ride_time_0012_alter_ride_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="destination",
            field=django_google_maps.fields.AddressField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ride",
            name="origin",
            field=django_google_maps.fields.AddressField(max_length=100),
        ),
    ]
