# Generated by Django 4.1.5 on 2023-02-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpool", "0014_alter_ride_destination_alter_ride_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="destination",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ride", name="origin", field=models.CharField(max_length=100),
        ),
    ]
