# Generated by Django 4.1.5 on 2023-02-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0015_alter_ride_destination_alter_ride_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('next_update', models.DateTimeField()),
                ('gas_price', models.FloatField()),
            ],
        ),
    ]
