# Generated by Django 4.1.5 on 2023-03-05 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0017_ride_rider_destination_ride_rider_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='rider_destination',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='rider_origin',
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpool.ride')),
            ],
        ),
    ]
